#!/usr/bin/env bash
# Stage 55 — check that Swift's pointer-alignment contracts actually hold on the target.
#
# Swift declares, for many AST types, how many spare low bits a pointer to them has:
#
#   LLVM_DECLARE_TYPE_ALIGNMENT(swift::TypeBase, swift::TypeAlignInBits)
#
# Nothing verifies that the type is really that aligned. On a 64-bit host the promise is
# often satisfied by accident — two pointers give natural alignment 8, which is the 3
# bits usually claimed — and the same type on a 32-bit host has alignment 4 and silently
# breaks every pointer packed with it. That failure mode is nasty: no assertion fires,
# pointers come back subtly wrong, and the symptom is a crash or garbled data far from
# the cause.
#
# This generates a static_assert per contract and compiles it for the wasm target. It is
# how both 32-bit bugs in this patch series were found:
#
#   * AbstractConformance promised 3 bits with natural alignment 4 (crash in mangling)
#   * CompoundDeclName used alignas(Identifier) — the alignment of a `const char *`,
#     8 only on 64-bit — while DeclName promised 2 spare bits on top of a tag bit
#     (garbled identifiers in diagnostics)
#
# Note: swift::SILFunctionType fails this check on *every* host, 64-bit included. It is a
# pre-existing upstream inconsistency that nothing appears to exercise, so it is reported
# rather than treated as a wasm regression.
source "$(dirname "${BASH_SOURCE[0]}")/../env.sh"

: "${SWIFT_SRC:=${TC_SRC}/swift}"
GEN="${TC_BUILD}/alignment-contracts.cpp"
mkdir -p "$TC_BUILD"

[[ -f "${SWIFT_SRC}/include/swift/AST/TypeAlignments.h" ]] || die "swift sources missing"

log "generating contract assertions from TypeAlignments.h"
python3 - "$SWIFT_SRC" "$GEN" <<'PY'
import re, sys
swift_src, out = sys.argv[1], sys.argv[2]
header = open(f"{swift_src}/include/swift/AST/TypeAlignments.h").read()
pairs = re.findall(r'LLVM_DECLARE_TYPE_ALIGNMENT\(\s*([\w:]+)\s*,\s*([\w:]+)\s*\)', header)
# Types whose definitions are not reachable from the AST headers below.
skip = {"swift::FileUnit", "swift::PackConformance", "swift::SILFunction"}
checks = "\n".join(
    f'  static_assert(alignof({cls}) >= (size_t(1) << {align}),\n'
    f'                "{cls}: PointerLikeTypeTraits promises more spare low bits than "\n'
    f'                "the type\'s alignment provides");'
    for cls, align in pairs if cls not in skip)
open(out, "w").write(f'''// Generated by scripts/55-check-alignment-contracts.sh — do not edit.
#include "swift/AST/ASTContext.h"
#include "swift/AST/Attr.h"
#include "swift/AST/Decl.h"
#include "swift/AST/Expr.h"
#include "swift/AST/GenericEnvironment.h"
#include "swift/AST/Identifier.h"
#include "swift/AST/Pattern.h"
#include "swift/AST/ProtocolConformance.h"
#include "swift/AST/Stmt.h"
#include "swift/AST/TypeRepr.h"
#include "swift/AST/Types.h"
#include <cstddef>
using namespace swift;
namespace {{
void checkAlignmentContracts() {{
{checks}
}}
}}
''')
print(f"{len(pairs)} contracts, {len(skip)} skipped as unreachable")
PY

log "compiling the assertions for ${WASM_TARGET}"
"${WASI_SDK_PATH}/bin/clang++" --target="${WASM_TARGET}" -std=c++17 \
  -fno-exceptions -fno-rtti -fsyntax-only "$GEN" \
  -D_WASI_EMULATED_MMAN -D_WASI_EMULATED_SIGNAL \
  -D_WASI_EMULATED_PROCESS_CLOCKS -D_WASI_EMULATED_GETPID \
  -I "${SWIFT_SRC}/include" \
  -I "${TC_BUILD}/wasm-swift/include" \
  -I "${LLVM_SRC}/llvm/include" \
  -I "${TC_BUILD}/wasm-llvm/include" \
  -I "${LLVM_SRC}/clang/include" \
  -I "${TC_BUILD}/wasm-llvm/tools/clang/include" \
  -I "${SWIFT_SRC}/stdlib/public/SwiftShims" \
  -I "${TC_SRC}/swift-cmark/src/include" \
  -I "${TC_BUILD}/wasm-cmark/src" \
  2>&1 | tee "${TC_BUILD}/alignment-contracts.log" | grep -E "static assertion failed" || true

if grep -q "static assertion failed" "${TC_BUILD}/alignment-contracts.log"; then
  # SILFunctionType fails on every host; anything else is a real 32-bit hazard.
  if grep "static assertion failed" "${TC_BUILD}/alignment-contracts.log" |
     grep -qv "SILFunctionType"; then
    die "an alignment contract is violated on ${WASM_TARGET}"
  fi
  warn "only the known-upstream SILFunctionType contract fails"
fi

log "alignment contracts hold"
